version: "3"
services:
  server:
    build:
      context: ./
    ports:
      - "${PORT}:${PORT}"
    env_file:
     - .env
    command: bash -c "ray start --head --redis-port=${PORT} && sleep infinity"
    shm_size: 4g
  client:
    build:
      context: ./
    env_file:
     - .env
    command: bash -c "ray start --redis-address=${HOST}:${PORT} && sleep infinity"
    shm_size: 4g
  develop:
    build:
      context: ./
    env_file:
     - .env
    volumes:
      - ./workspace:/workspace
    
