version: "3"
services:
  server:
    build:
      context: ./
    ports:
      - "${PORT}:${PORT}"
    env_file:
     - .env
    command: bash -c "ray start --head --redis-port=${PORT} && sleep infinity"
    shm_size: 4g
    networks:
      ray_net:
        ipv4_address: 172.63.0.2

  client:
    build:
      context: ./
    env_file:
     - .env
    command: bash -c "ray start --redis-address=${HOST}:${PORT} && sleep infinity"
    shm_size: 4g
    networks:
      ray_net:
        ipv4_address: 172.63.0.${IP}
  develop:
    build:
      context: ./
    env_file:
     - .env
    volumes:
      - ./workspace:/workspace
    networks:
      ray_net:
        ipv4_address: 172.63.0.${IP}
    
networks:
  ray_net:
    ipam:
      driver: default
      config:
        - subnet: 172.63.0.0/16
