version: "3"
services:
  server:
    build:
      context: ./
    ports:
      - "${REDISPORT}:${REDISPORT}"
      - "${OBJECTMANAGERPORT}:${OBJECTMANAGERPORT}"
    env_file:
     - .env
    command: bash -c "ray start --head --object-manager-port=${OBJECTMANAGERPORT} --redis-port=${REDISPORT} --num-workers=${WORKERS} && sleep infinity"
    shm_size: 4g
    network_mode: "host"
    #networks:
    #  ray_net:
    #    ipv4_address: 172.63.0.2

  client:
    build:
      context: ./
    ports:
      - "${OBJECTMANAGERPORT}:${OBJECTMANAGERPORT}"
    env_file:
     - .env
    command: bash -c "ray start --object-manager-port=${OBJECTMANAGERPORT} --redis-address=${HOST}:${REDISPORT} --num-workers=${WORKERS} && sleep infinity"
    shm_size: 4g
    network_mode: "host"
    #networks:
    #  ray_net:
    #    ipv4_address: 172.63.0.${IP}
  develop:
    build:
      context: ./
    env_file:
     - .env
    volumes:
      - ./workspace:/workspace
    network_mode: "host"
    #networks:
    #  ray_net:
    #    ipv4_address: 172.63.0.${IP}
    
networks:
  ray_net:
    ipam:
      driver: default
      config:
        - subnet: 172.63.0.0/16
